# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: &name Ramon Gonçalves Gonze
email: ramon.gonze@inria.fr
description: &description | # this means to ignore newlines until "baseurl:"
  I am a PhD student in computer science in cotutelle between École Polytechnique de Paris (France) and Universidade Federal de Minas Gerais (Brazil) under the supervision of Prof. <a href="https://scholar.google.com/citations?user=OOgAyqgAAAAJ&hl=en" target="_blank">Catuscia Palamidessi</a> and <a href="https://scholar.google.com.br/citations?user=9r8YfCgAAAAJ&hl=en&oi=ao" target="_blank">Mário S. Alvim</a>.
  <br><br>
  My reserach interesets include responsible computing, privacy, Quantitative Information Flow (QIF), differential privacy and information theory.
  <br><br>
  More about QIF: <a href="https://topete.science">Topete Research Group</a>.
github_username: ramongonze
minimal_mistakes_skin: dark
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

breadcrumbs: true  # Add the path of pages
enable_copy_code_button: true # Copy button in code blocks

author:
  name   : *name
  avatar : "/assets/images/bio-photo.jpg"
  email: "(\u03BBw.\u03BBx@\u03BBy.\u03BBz) ramon gonze inria fr"
  cv: "assets/files/CV_Ramon.pdf"
  bio    : "PhD student in computer science"
  location: Belo Horizonte, Brazil
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ramongonze"
    - label: "Google Scholar"
      icon: "fa-brands fa-google-scholar"
      url: "https://scholar.google.com/citations?user=OHffUYgAAAAJ&hl=pt-BR&oi=ao"
    - label: "ORCID"
      icon: "fa-brands fa-orcid"
      url: "https://orcid.org/my-orcid?orcid=0009-0003-3247-3064"
    - label: "Linkedin"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/ramongonze"
    - label: "Lattes"
      icon: "ai ai-lattes"   # pick any Font Awesome class you like
      url: "http://lattes.cnpq.br/4271248191436145"

atom_feed: # Hide feed icon in the footer
  hide: true
# footer:

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      date_format: "%Y-%m"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: news
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true

# These settings control the types of collections used by the template
collections:
  news:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:path/
    